import "server-only";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

/**
 * The bundled demo catalogue — what the app serves when no upstream service is
 * configured.
 *
 * A fresh clone has no `BACKEND_API_URL`, and an app that greets you with an
 * empty grid and a network error is not a demo, it is a bug report waiting to
 * happen. So the absence of a backend is treated as a supported configuration
 * rather than a failure: the catalogue is read from `data/channels.json` and the
 * playable links from `data/verified-sources.json`, both generated by
 * `npm run demo:data`.
 *
 * Set `BACKEND_API_URL` and this module is never consulted — the real proxy path
 * takes over unchanged. Nothing here is a stub of the real thing; it is a second
 * source for the same shape.
 */

export interface CatalogChannel {
  name: string;
  online: boolean;
  category?: string;
  logo?: string;
  logo_url?: string;
  primary_url?: string;
  backup_urls?: string[];
}

/** True when the app should serve its own bundled catalogue. */
export function usingDemoCatalog(): boolean {
  return !process.env.BACKEND_API_URL;
}

let cache: CatalogChannel[] | null = null;

/**
 * Read `data/channels.json`.
 *
 * Cached after the first read: the file ships with the build and cannot change
 * underneath a running server, so re-reading it per request would be pure I/O
 * for an identical answer. Returns `[]` (never throws) so a missing or corrupt
 * file degrades to an empty grid instead of a 500 — the page still renders and
 * the server log carries the reason.
 */
export async function loadDemoChannels(): Promise<CatalogChannel[]> {
  if (cache) return cache;

  const path = resolve(process.cwd(), "data/channels.json");
  try {
    const parsed = JSON.parse(await readFile(path, "utf-8"));
    cache = Array.isArray(parsed) ? (parsed as CatalogChannel[]) : [];
  } catch (err) {
    console.error(
      `[demoCatalog] could not read ${path}:`,
      err instanceof Error ? err.message : String(err),
    );
    cache = [];
  }
  return cache;
}

export interface DemoVodItem {
  tmdb_id: number;
  title: string;
  year?: string;
  overview?: string;
  service: string;
  media_type?: string;
}

export interface DemoVodCatalog {
  services: string[];
  summary: Record<
    string,
    { movies_count: number; series_count: number; preview: { tmdb_id: number; name: string }[] }
  >;
  movies: DemoVodItem[];
  series: DemoVodItem[];
}

let vodCache: DemoVodCatalog | null = null;

/** Read `data/vod-catalog.json` — browse metadata for the bundled titles.
 *  Same contract as loadDemoChannels: cached, never throws. */
export async function loadDemoVodCatalog(): Promise<DemoVodCatalog> {
  if (vodCache) return vodCache;

  const empty: DemoVodCatalog = { services: [], summary: {}, movies: [], series: [] };
  const path = resolve(process.cwd(), "data/vod-catalog.json");
  try {
    vodCache = { ...empty, ...JSON.parse(await readFile(path, "utf-8")) };
  } catch (err) {
    console.error(
      `[demoCatalog] could not read ${path}:`,
      err instanceof Error ? err.message : String(err),
    );
    vodCache = empty;
  }
  return vodCache ?? empty;
}
